### ISSUE TITLE
No items 

### ISSUE THREAD

**Issue by f3f00cb0** [ImMacky/mk-atmRobbery#2]
Items dosn't exist when trying to give

**Comment by f3f00cb0** [comment]
My bad didn't add the` ['rfid_disruptor']              = {['name'] = 'rfid_disruptor',               ['label'] = 'RFID Disruptor',        ['weight'] = 1000,         ['type'] = 'item',      ['image'] = 'rfid_disruptor.png',      ['unique'] = false,      ['useable'] = true,     ['shouldClose'] = false,   ['combinable'] = nil,   ['description'] = ' A Disruptor used for ATM firewalls'}, `lines

**Comment by f3f00cb0** [comment]
After the plugging in disruptor nothings happens

**Comment by ImMacky** [comment]
Have you included all the code snippets and prerequisites in the README?
